### ISSUE TITLE
[Bug] Mount images, cannot find valid erofs superblock

### ISSUE THREAD

**Issue by imre1107** [LSPosed/MagiskOnWSALocal#648] opened 2023-08-05 18:09 UTC
### Steps to reproduce/复现步骤

1. Run the command ./run.sh

### Expected behaviour/预期行为

![Screenshot 2023-08-05 152703](https://github.com/LSPosed/MagiskOnWSALocal/assets/89696220/b34144b3-4c37-4a48-b202-46bbef1f39df)

### Actual behaviour/实际行为

error

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

da39a3ee5e6b4b0d3255bfef95601890afd80709

### Linux distribution info/Linux 发行版信息

No LSB modules are available.                                                                           
Distributor ID: Debian                                                                                  
Description:    Debian GNU/Linux 12 (bookworm)                                                          
Release:        12                                                                                      
Codename:       bookworm

Kernel version: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64
   
WSL version: 1.15.0.0

### Windows version/Windows 版本

22000.2245

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon                
INFO: Architecture: x64                                                                                                 
INFO: Release Type: retail                                                                                              
INFO: Magisk Version: stable                                                                                            
INFO: GApps Brand: MindTheGapps                                                                                         
INFO: GApps Variant: pico                                                                                               
INFO: Root Solution: none                                                                                               
Build: RELEASE_TYPE=Retail                                                                                              
Generate Download Links 
Generating WSA download link: arch=x64 release_type=Retail
WSA Build Version=2306.40000.4.0 

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by JohnnyAntunes** [comment] 2023-08-05 21:05
me too

`Extract done

Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-USehKID0UP_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-USehKID0UP_/erofs
dbglevel: 0
<E> erofs: cannot find valid erofs superblock
failed to read erofs super block
Build: an error has occurred, exit`

**Comment by k4ever** [comment] 2023-08-06 15:13
I have the same issue:

Extract done

Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-mwb96hQKe8_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-mwb96hQKe8_/erofs
dbglevel: 0
<E> erofs: cannot find valid erofs superblock
failed to read erofs super block
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-mwb96hQKe8_/erofs/vendor: no mount point specified.
umount: /tmp/wsa-build-mwb96hQKe8_/erofs/system_ext: no mount point specified.
umount: /tmp/wsa-build-mwb96hQKe8_/erofs/product: no mount point specified.
umount: /tmp/wsa-build-mwb96hQKe8_/erofs: not mounted.
umount: /tmp/wsa-build-mwb96hQKe8_/system_root_merged/vendor: no mount point specified.
umount: /tmp/wsa-build-mwb96hQKe8_/system_root_merged/system_ext: no mount point specified.
umount: /tmp/wsa-build-mwb96hQKe8_/system_root_merged/product: no mount point specified.
umount: /tmp/wsa-build-mwb96hQKe8_/system_root_merged: no mount point specified.
deactivate python3 venv
Cleanup Download Directory

I'm running this on a ASUS ROG Strix GL-702VM with EndeavourOS (Arch) installed. I also had the same issue running on a Surface Pro 8 with EndeavourOS installed.

**Comment by andmpel** [comment] 2023-08-06 16:00
I'm having the same issue using ubuntu wsl on windows 11

**Comment by k4ever** [comment] 2023-08-06 17:46
Our issue seems to be a duplicate of this issue:

https://github.com/LSPosed/MagiskOnWSALocal/issues/615

To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:

https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files

Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

**Comment by boludoz** [comment] 2023-08-10 19:07
Works sir

**Comment by stealthman22** [comment] 2023-08-14 11:10
> 

Works like magic. 
N.B: Mind the spacing before the closing parenthesis guys, it should be :
`if [[ "$WSA_MAJOR_VER" -lt 2304 || "$WSA_MAJOR_VER" -ge 2306 ]]`
not
`if [[ "$WSA_MAJOR_VER" -lt 2304 || "$WSA_MAJOR_VER" -ge 2306]]`

It could cause an error.

Might I ask @k4ever  what these lines actually do, and why did we have to add them in?

**Comment by YT-Advanced** [comment] 2023-08-14 12:06
Sorry because I have busy with my other project (ReX). I will update the script to fully compatiable with all version !

**Comment by k4ever** [comment] 2023-08-15 01:06
> > 
> 
> Works like magic. N.B: Mind the spacing before the closing parenthesis guys, it should be : `if [[ "$WSA_MAJOR_VER" -lt 2304 || "$WSA_MAJOR_VER" -ge 2306 ]]` not `if [[ "$WSA_MAJOR_VER" -lt 2304 || "$WSA_MAJOR_VER" -ge 2306]]`
> 
> It could cause an error.
> 
> Might I ask @k4ever what these lines actually do, and why did we have to add them in?

IDK what they do. I just followed the post. Be best to ask the originator of the post.

**Comment by stealthman22** [comment] 2023-08-16 01:54
Thanks  man
next up is how to move it to my hard disk, my ssd is only 256.
I've got wsl already too

**Comment by SynapticMindset** [comment] 2023-08-18 16:11
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

work to me thank u

**Comment by cofisufu** [comment] 2023-08-18 17:25
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

Works like magic

Thank you!

**Comment by BRJB** [comment] 2023-08-21 14:28
I edited the three lines of the build script but when I run it, it gives the  error reported as bug #642. 
"Add device administration features
sed: can't read /tmp/wsa-build-PsdF23Ka6O_/system_root_merged/vendor/etc/permissions/windows.permissions.xml: No such file or directory" #642

What is fix for this??

**Comment by mnksauce** [comment] 2023-08-21 18:28
> 

This just happened to me. Make sure you copied the right row of text for 675. It's not the same as the other two.

**Comment by Wanxp** [comment] 2023-08-25 05:45
> I edited the three lines of the build script but when I run it, it gives the error reported as bug #642. "Add device administration features sed: can't read /tmp/wsa-build-PsdF23Ka6O_/system_root_merged/vendor/etc/permissions/windows.permissions.xml: No such file or directory" #642
> 
> What is fix for this??

I meet this error too

**Comment by franmen05** [comment] 2023-08-29 04:59
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

yeahhhh!!
work!!

**Comment by MQuirosP** [comment] 2023-09-07 19:11
not working for me

**Comment by zolakk** [comment] 2023-09-20 19:19
It wasn't working for me until I double checked the changes and I put a && instead of || on 675 by mistake. There is also a -ge instead of an -lt like the other lines.

**Comment by Anz-03** [comment] 2023-09-21 11:22
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

It works for me. Thanks!

**Comment by babyedi3** [comment] 2023-10-06 16:37
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

U R my hero

**Comment by Creomortis** [comment] 2023-10-15 18:35
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

Thank you so much, fixed it for me too.

**Comment by willie0175** [comment] 2023-10-17 18:30
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

Not working for me. Copied and pasted the lines and now getting the error message that it "fails to read" the erofs. Any advise on what I may have done wrong?

**Comment by Tom747-400** [comment] 2023-10-24 05:45
> Our issue seems to be a duplicate of this issue:
> 
> #615
> 
> To fix it, you have to go to the MagiskOnWSALocal/scripts/ directory and edit 3 lines in the build.sh file (lines 651, 675, and 909) to match this:
> 
> https://github.com/LSPosed/MagiskOnWSALocal/pull/620/files
> 
> Afterwards, re-run the build.sh script. I got mine to successfully build with these changes.

Thanks so much. It works!

**Closed** 2024-03-03 17:39 UTC
Labels: bug
