### ISSUE TITLE
[Bug] lspinit branch doesn't work properly

### ISSUE THREAD

**Issue by s1204IT** [LSPosed/MagiskOnWSALocal#774] opened 2024-02-27 05:41 UTC
### Steps to reproduce

```
git clone git@github.com:LSPosed/MagiskOnWSALocal --de 1
```
That is, the main branch.

Also, another repository used in the code is not yet published.
<https://github.com/LSPosed/MagiskOnWSALocal/blob/44df7ca/scripts/generateGappsLink.py#L39>

### Expected behaviour

Perhaps the new method will allow you to build WSA correctly.

### Actual behaviour

The argument is incorrect and the build cannot continue.

### MagiskOnWSALocal commit full SHA

44df7ca8ac4a755d05abe11ba44d621414b2a537

### Linux distribution info

Ubuntu-22.04

### Windows version

10.0.22631.3155

### Build Parameters

COMMAND_LINE=--arch x64 --release-type WIF --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable

### Version requirement

- [X] I am using latest commit of MagiskOnWSALocal

### Logs

<details>

[//]: <> (Don't modify above)

The `lspinit` branch is set to main, but it doesn't work properly with the current configuration.

```
COMMAND_LINE=--arch x64 --release-type WIF --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable
build.sh: unrecognized option '--gapps-brand'
build.sh: unrecognized option '--remove-amazon'
ERROR: Failed to parse options, please check your input

Usage:
    --arch              Architecture of WSA.

                        Possible values: x64, arm64
                        Default: x64

    --release-type      Release type of WSA.
                        RP means Release Preview, WIS means Insider Slow, WIF means Insider Fast.

                        Possible values: retail, RP, WIS, WIF
                        Default: retail

    --magisk-ver        Magisk version.

                        Possible values: stable, beta, canary, debug, release
                        Default: stable

    --root-sol          Root solution.
                        "none" means no root.

                        Possible values: magisk, kernelsu, none
                        Default: magisk

    --compress-format   Compress format of output file.

                        Possible values: 7z, zip, none
                        Default: none

Additional Options:
    --offline           Build WSA offline
    --magisk-custom     Install custom Magisk
    --skip-download-wsa Skip download WSA
    --help              Show this help message and exit

Example:
    ./build.sh --release-type RP --magisk-ver beta
    ./build.sh --arch arm64 --release-type WIF
    ./build.sh --release-type WIS
    ./build.sh --offline --magisk-custom
    ./build.sh --release-type WIF --magisk-custom --magisk-ver release
```

Even if I specify the arguments correctly within the possible range, it will not work.
```
user@host:~/MagiskOnWSALocal$ ./scripts/build.sh --release-type WIF
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: Root Solution: magisk
INFO: Compress Format: none
INFO: Release Name: Insider Fast

Generating WSA Download Links
Generating WSA download link: arch=x64 release_type=Insider Fast

WSA Build Version=2311.40000.5.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/3695a927-e7a8-4d4e-9115-d750aee8faac?P1=1709012866&P2=404&P3=2&P4=Szg%2biZ5u0Pd4Y%2bU2y5oqrzeDfgo6ggTG9iQubkB8jlcTVRPwreP72pEhvOrC2%2f8V7S2kwRUVnEc0RmxAEngmRg%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/251bbb12-dbfc-4820-b0ff-c4dfa70ffb09?P1=1709012872&P2=404&P3=2&P4=Vm31IiwSLVWeuzUXc3Pnstvj7%2fO81vxxDS7kT2Mvy8dyhE%2bOOFepMEo0d8ohfYQOxs5wIn2xqbOiAKi7u%2f3sGw%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/9f21fa47-fe2c-4f89-804e-e2b697f0bb14?P1=1709040848&P2=404&P3=2&P4=ZR43OL7J5vwedZG3ptpiv%2bt6cSor15pARfCFX7e3BzNwnqkoDYtmuAWohBMLbhpMaztNCSzE70MqSPHqltLM8A%3d%3d
path: ../download/wsa-WIF.zip

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/c452d4ef-2486-4efe-9c99-36b3d23e0160?P1=1709012797&P2=404&P3=2&P4=EbmVy4x324O%2fQ950io8XPUAStedcovFAGuS%2fwhkDFHrnDG1HfyPO6F%2bUCnsuU2yBydMOfnKT2zEOgPuxDWzIGg%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

Downloading WSA

02/27 14:36:28 [NOTICE] Downloading 4 item(s)

02/27 14:36:29 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx
[DL:32MiB][#80e86b 2.4MiB/6.4MiB(37%)][#720b01 2.9MiB/4.8MiB(59%)][#55172f 10MiB/1.3GiB(0%)]
02/27 14:36:30 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx
[DL:12MiB][#80e86b 4.1MiB/6.4MiB(64%)][#55172f 23MiB/1.3GiB(1%)]
02/27 14:36:31 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
 *** Download Progress Summary as of Tue Feb 27 14:37:29 2024 ***
================================================================================================================================================================================================================
[#55172f 673MiB/1.3GiB(47%) CN:16 DL:11MiB ETA:1m4s]
FILE: ../download/wsa-WIF.zip
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Tue Feb 27 14:38:29 2024 ***
================================================================================================================================================================================================================
[#55172f 1.3GiB/1.3GiB(96%) CN:12 DL:11MiB ETA:4s]
FILE: ../download/wsa-WIF.zip
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

[#55172f 1.3GiB/1.3GiB(99%) CN:2 DL:11MiB]
02/27 14:38:33 [NOTICE] Download complete: ../download/wsa-WIF.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
1047aa|OK  |    10MiB/s|../download/Microsoft.VCLibs.140.00_x64.appx
720b01|OK  |   3.8MiB/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
80e86b|OK  |   2.2MiB/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
55172f|OK  |    11MiB/s|../download/wsa-WIF.zip

Status Legend:
(OK):download completed.
Extracting WSA
unzipping WsaPackage_2311.40000.5.0_x64_Release-Nightly.msix to /tmp/wsa-build-Lfd6f1TRDL_/wsa
unzipping from /tmp/wsa-build-Lfd6f1TRDL_/wsa/WsaPackage_2311.40000.5.0_x64_Release-Nightly.msix
done

Generating Download Links
Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@27.0/app-release.apk
Downloading Artifacts

02/27 14:38:53 [NOTICE] Downloading 1 item(s)

02/27 14:38:53 [NOTICE] Download complete: ../download/magisk-stable.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d403eb|OK  |    63MiB/s|../download/magisk-stable.zip

Status Legend:
(OK):download completed.
Extracting Magisk
Magisk version: 27.0 (27000)
done

Integrating Magisk
Loading cpio: [/tmp/wsa-build-Lfd6f1TRDL_/wsa/x64/Tools/initrd.img]
Move [/init] -> [/wsainit]
No such file or directory (os error 2)
Failed to process cpio
ERROR: Unable to patch initrd
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Download Directory
```

[//]: <> (Don't modify below)
</details>

**Comment by Anivie** [comment] 2024-02-27 16:54
same problem

**Comment by trimeta** [comment] 2024-02-27 17:21
This issue is a duplicate of #773 (unless your error message differs from the one there, @s1204IT, in which case please elaborate).

**Closed** 2024-03-03 02:59 UTC
Labels: bug
