### ISSUE TITLE
Download folder with wsa-x64.zip is created in the parent directory

### ISSUE THREAD

**Issue by h4wwk3ye** [LSPosed/MagiskOnWSALocal#114] opened 2022-09-16 14:21 UTC
![Screenshot 2022-09-16 194958](https://user-images.githubusercontent.com/24487030/190661180-70e7d7b7-2a6b-4d9d-8e8b-1894ea72e959.png)

A second download folder in the parent directory was created as well

**Comment by Howard20181** [comment] 2022-09-16 14:34
Unable to reproduce, please check if the local repository is up-to-date.
![image](https://user-images.githubusercontent.com/40033067/190663836-cf82708d-ea58-46dc-a689-239abf2ff7d7.png)

**Comment by s1204IT** [comment] 2022-09-16 16:04
![image](https://user-images.githubusercontent.com/52069677/190681615-54e746df-e295-43f2-8198-e3e59d45e51a.png)

However, the same thing is happening in my environment.

Of course the content of the repository is up to date.

**Comment by Howard20181** [comment] 2022-09-16 17:00
My bad, fixed in 823f1895d0c8e408b6f481967ea900230a0ede9c

**Closed by Howard20181** 2022-09-16 17:00 UTC
Labels: bug
