### ISSUE TITLE
[Bug] error 0x80073B17 when trying to install

### ISSUE THREAD

**Issue by sweterere** [LSPosed/MagiskOnWSALocal#470] opened 2023-04-01 20:43 UTC
### Steps to reproduce/复现步骤

1. Do step 1-11 from the [Text guide](https://github.com/LSPosed/MagiskOnWSALocal#text-guide)
2. Run `Install.ps1` via the command `PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1`

### Expected behaviour/预期行为

MagiskOnWSA should install

### Actual behaviour/实际行为

A cmd window appears saying that it can't register the packet, with error code 0x80073B17

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

04c90295061af65fcf9359ea5cb5383cb195e310

### Linux distribution info/Linux 发行版信息

Ubuntu

### Windows version/Windows 版本

10.0.22621.1413

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico  --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
WSA Version=2302.40000.9.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Time                      ID           Message
----                      --           -------
01.04.2023, sobota 22:27: 603          Rozpoczęto operację wdrażania Register na pakiecie z głównym AppxManifest.xml z parametrami i opcjami ForceApplicationShutdownOption,DevelopmentModeOption,ForceUpdateFro
27                                     mAnyVersion i 0. Zobacz http://go.microsoft.com/fwlink/?LinkId=235160, aby uzyskać pomoc w diagnozowaniu problemów z wdrażaniem aplikacji.
01.04.2023, sobota 22:27: 216          App manifest validation warning: Declared namespace http://schemas.microsoft.com/developer/appx/2015/build is inapplicable, it will be ignored during manifest processing
27                                     .
01.04.2023, sobota 22:27: 10002        Trwa tworzenie pliku o odporności C:\ProgramData\Microsoft\Windows\AppRepository\267da7e9-4e64-4403-88b0-935efe835bf9_S-1-5-21-2526595594-4244064583-3226672986-1001_25.r
27                                     slc dla Register operacji na pakiecie MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe.
01.04.2023, sobota 22:27: 607          Operacja Register wdrażania na pakiecie MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe została umieszczona w kolejce i jest uruchomi
27                                     ona na potrzeby S-1-5-21-2526595594-4244064583-3226672986-1001 identyfikatora SID użytkownika.
01.04.2023, sobota 22:27: 854          Pomyślnie dodano następujące identyfikatory URI:  D:\wsa_g\wsaG\AppxManifest.xml.
27
01.04.2023, sobota 22:27: 855          Ukończono rozwiązywanie list akcji. Listy akcji DeploymentRequest:  addPackageList: MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe.
28
01.04.2023, sobota 22:27: 333          D:\wsa_g\wsaG\AppxManifest.xml (85, 27): błąd 0x80073B17: nie można zarejestrować pakietu MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8
28                                     bbwe, ponieważ napotkano następujący błąd podczas ustalania, czy można lokalizować zasób ciągu ms-resource:WsaDisplayName: Nie znaleziono parametru NamedResource.
                                       . Sprawdź, czy został zdefiniowany zasób ciągu i czy w pliku zasobów. pri znajduje się co najmniej jedno wystąpienie zdefiniowane w pliku Resources. pri w tym pakiecie.
01.04.2023, sobota 22:27: 6902         AppxManifest.xml (84, 6): błąd 0x80073B17: nie można zarejestrować pakietu MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe, ponieważ
28                                     napotkano następujący błąd podczas analizowania aplikacji App: Nie znaleziono parametru NamedResource.
                                       .  Spróbuj ponownie, a jeśli problem będzie nadal występował, skontaktuj się z wydawcą pakietu.
01.04.2023, sobota 22:27: 6901         AppxManifest.xml (102, 10): błąd 0x80073B17: nie można zarejestrować pakietu MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe, poniewa
28                                     ż napotkano następujący błąd podczas analizowania elementu windows.appExecutionAlias rozszerzenia: Nie znaleziono parametru NamedResource.
                                       .  Spróbuj ponownie, a jeśli problem będzie nadal występował, skontaktuj się z wydawcą pakietu.
01.04.2023, sobota 22:27: 6800         AppxManifest.xml (104, 14): błąd 0x80073B17: nie można zarejestrować pakietu MicrosoftCorporationII.WindowsSubsystemForAndroid, ponieważ napotkano następujący błąd podcz
28                                     as analizowania rozszerzenia windows.appExecutionAlias: Nie znaleziono parametru NamedResource.
                                       .  Spróbuj ponownie, a jeśli problem będzie nadal występował, skontaktuj się z wydawcą pakietu.
01.04.2023, sobota 22:27: 303          błąd 0x80073B17: podczas przygotowywania do przetworzenia żądania system nie może zarejestrować rozszerzenia windows.appExecutionAlias z powodu następującego błędu: Nie
28                                     znaleziono parametru NamedResource.
                                       .
01.04.2023, sobota 22:27: 300          błąd 0x80073B17: nie można zarejestrować pakietu MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe z powodu następującego błędu: Nie znaleziono parametru N
28                                     amedResource.
                                       .
01.04.2023, sobota 22:27: 605          Ostatni osiągnięty stan powodzenia został MutablePackageDirectoryAdd. Wystąpił błąd przed osiągnięciem następnego MachineRegisterAdd stanu. HR:  0x80073CF6
28
01.04.2023, sobota 22:27: 401          Operacja Register wdrażania z woluminem docelowym D: na pakiecie MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe z:  (AppxManifest.xm
28                                     l)  zakończyła się niepowodzeniem z powodu błędu 0x80073CF6. Zobacz http://go.microsoft.com/fwlink/?LinkId=235160, aby uzyskać pomoc w diagnozowaniu problemów z wdrażani
                                       em aplikacji.
01.04.2023, sobota 22:27: 404          Operacja wdrażania aplikacji AppX dla pakietu MicrosoftCorporationII.WindowsSubsystemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe nie powiodła się. 0x80073CF6 błędu. W p
28                                     rzypadku tego błędu jest podany tekst błędu:  D:\wsa_g\wsaG\AppxManifest.xml (85, 27): błąd 0x80073B17: nie można zarejestrować pakietu MicrosoftCorporationII.WindowsSub
                                       systemForAndroid_2302.40000.9.0_x64__8wekyb3d8bbwe, ponieważ napotkano następujący błąd podczas ustalania, czy można lokalizować zasób ciągu ms-resource:WsaDisplayName:
                                       Nie znaleziono parametru NamedResource.
                                       . Sprawdź, czy został zdefiniowany zasób ciągu i czy w pliku zasobów. pri znajduje się co najmniej jedno wystąpienie zdefiniowane w pliku Resources. pri w tym pakiecie.

```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment] 2023-04-01 23:33
Duplicate of #450
Fixed
Please update the build script and rebuild

**Closed by Howard20181** 2023-04-01 23:33 UTC
Labels: bug
